name: Bookkeeping update
description: File a change request to your Bookkeeping repo in Github 
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this change request!
  - type: input
    id: contact
    attributes:
      label: Organization
      description: What is your Organization?
      placeholder: ex. Filecoin Foundation
    validations:
      required: false
  - type: textarea
    id: What is the New Address
    attributes:
      label: Updated URL to the Bookkeeping repo you would like linked to your JSON for the Allocator Organization
      description: What is the new address you would like to list for the Bookkeeping?
      placeholder: Tell us what you see!
      value: "Bookkeeping address"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What is the Application number for your organization?
      multiple: true
      options:
        - 1001
        - 1003
        - 1001
        - 1003
        - 1004
        - 1005
        - 1006
        - 1007
        - 1009
        - 1010
        - 1012
        - 1013
        - 1014
        - 1015
        - 1016
        - 1017
        - 1019
        - 1020
        - 1022
        - 1023
        - 1024
        - 1025
        - 1026
        - 1027
        - 1028
        - 1029
        - 1030
        - 1033
        - 1034
        - 1035
        - 1038
        - 1039
        - 1040
        - 1041
        - 1042
        - 1044
        - 1045
        - 1046
        - 1047
        - 1048
        - 1050
        - 1052
        - 1053
        - 1054
        - 1056
        - 1057
        - 1058
        - 1059
        - 1060
        - 1064
        - 1065
        - 1067
        - 1068
        - 1069
        - 1070
        - 1071
        - 1073
        - 1074
        - 1075
        - 1076
        - 1077
        - 1078
        - 1080
        - 1081
        - 1083
        - 1084
        - 1085
        - 1086
        - 1088
        - 1089
        - 1091
        - 1092
        - 1093
        - 1094
        - 1095
        - 1096
        - 1097
        - 1099
        - 990
        - 992
        - 996
        - 997
  - type: textarea
    id: logs
    attributes:
      label: Any adittional details
      description: Please provide any additional details for this request?
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: By submitting this issue, you confirm that your GITHUB account is already registered with the Organization. 
      options:
        - label: The Github used to file this ticket is also the same Github ID that is connected to the Organization
          required: true
