blank_issues_enabled: false
contact_links:
  - name: Allocator Applications
    url: https://allocator.tech/
    about: See open and pending DataCap applications here.
  - name: Allocator Governance
    url: https://github.com/filecoin-project/Allocator-Governance
    about: Please review program overview here.
