name: Bookkeeping Repo Change
description: Allocators should use this form to submit a request to change the Bookkeeping Github repo for their diligence checks.
title: "[DataCap Application] <Organization> - <Project Name>"
body:
- type: markdown
  attributes:
    value: |
      # Large Dataset Notary Application
      To apply for DataCap to onboard your dataset to Filecoin, please fill out the following form
- type: dropdown
  id: version
  attributes:
      label: Version
      description: Schema File Version
      options:
        - 1
  validations:
    required: true


name: Allocator JSON Update
description: Submit to file a request for support to update fields for your Organization
title: "[Allocator Change]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - Kevin-ff-usa
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. kevin-ff-usa
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true




name: Large Dataset Datacap Application v1.2
description: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "[DataCap Application] <Organization> - <Project Name>"
body:
- type: markdown
  attributes:
    value: |
      # Large Dataset Notary Application
      To apply for DataCap to onboard your dataset to Filecoin, please fill out the following form
- type: dropdown
  id: version
  attributes:
      label: Version
      description: Schema File Version
      options:
        - 1
  validations:
    required: true
- type: input
  attributes:
    label: DataCap Applicant
  validations:
    required: true
- type: input
  attributes:
    label: Project ID
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      # Core Information
- type: input
  attributes:
    label: Data Owner Name
  validations:
    required: true
- type: dropdown
  attributes:
    label: Data Owner Country/Region
    options:
      - Afghanistan
      - Åland Islands
      - Albania
      - Algeria
      - American Samoa
      - Andorra
      - Angola
      - Anguilla
      - Antarctica
      - Antigua and Barbuda
      - Argentina
      - Armenia
      - Aruba
      - Australia
      - Austria
      - Azerbaijan
      
