name: "Github Account Update"
description: "Issue Template for submitting a request to modify the Github authorized for Allocator"
body:
- type: markdown
  attributes:
    value: |
      # Github Authorized account modification
      To change the Github account authorized for your Allocator please fill out the following form
- type: markdown
  attributes:
    value: |
      Application Info
- type: input
  attributes:
    label: Organization 
    description: The name of the Allocator Organization you are wishing to update an Authorized Github account for
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      # Applicaiton Number (The JSON #) for the Organization
- type: input
  attributes:
    label: Application Number
  validations:
    required: true
- type: input
  attributes:
    label: Updated Github  
    description: The name of the updated Github account you are wishing to update
  validations:
    required: true
- type: dropdown
  attributes:
    label: Would you like to 
    options:
      - Remove an existing Github Handle
      - Modify an existing Github Handle
      - Add new Github Handle
      - Other
- type: dropdown
  attributes:
    label: Please confirm that the Github Account used to file this request is already recorded on the Allocator JSON for your organization. 
    options:
      - "No"
      - "Yes"
  validations:
    required: true
- type: input
  attributes:
    label: Additional Information 
    description: Any additional information you with to provide?
  validations:
    required: false

        
